{
 "title": "Retrograde",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "HTTP Request Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(retrograde_http_requests_total{endpoint!=\"/_metrics\"}[10m]))"
    }
   ]
  },
  {
   "title": "HTTP Response Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(retrograde_http_requests_total{endpoint!=\"/_metrics\"}[10m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "HTTP Requests by Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(retrograde_http_requests_total{endpoint!=\"/_metrics\"}[10m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "HTTP Response Times",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(retrograde_http_requests_duration_seconds_bucket{endpoint!=\"/_metrics\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Resource Creation by Hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(retrograde_boards_total[1h]))",
     "legendFormat": "Boards"
    },
    {
     "expr": "sum(increase(retrograde_ranks_total[1h]))",
     "legendFormat": "Ranks"
    },
    {
     "expr": "sum(increase(retrograde_cards_total[1h]))",
     "legendFormat": "Cards"
    }
   ]
  }
 ]
}