CREATE TABLE card (
  id CHAR(16) PRIMARY KEY DEFAULT random_string(16),
  rank_id CHAR(16) REFERENCES rank ON DELETE CASCADE NOT NULL,
  name VARCHAR NOT NULL DEFAULT '',
  description VARCHAR NOT NULL DEFAULT ''
)